### ISSUE TITLE
minor requests!

### ISSUE THREAD

**Issue by yangsunhwang** [LorenFrankLab/rec_to_nwb_yaml_creator#20]
- map information was not saved as it is (I used 128c-4s6mm6cm-15um-26um-sl device_type and saved default map)
- Shank number should start from 0 instead of 1
- date_of_birth is saved as '2022-03-25T00:00:00.000Z' and makes error during nwb_generation
- data_acq_device minor typos
   name: Trodes    system: SpikeGadgets

**Comment by zoldello** [comment]
@yangsunhwang 

Can you show me how you saved the map information? It worked for me. 

By "Shank number", do you mean "NTrode Id"? If yes, why should it start at 0? The convention I learned was starting at 1

nwb_generation needs to be updated to comply with DANDI. Ask Eric about that

Let's talk about Trodes system. I reorganized and and corrected the spelling of SpikeGadget.
